kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
php: php?start_inline=1
collections:
  projects:
    output: true
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []
exclude: []
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
algolia:
  application_id: NMQ2IFNV6E
  index_name: opis_php
opis:
  url_prefix: ""
  favicon: /assets/img/favicon.png
  logo: /assets/img/logo.svg
  copyright: Copyright Â© Zindex Software. All rights reserved
  doc_source: https://github.com/opis/opis.github.io/tree/master
  nav:
    Home: "https://opis.io/"
    GitHub:
      url:
      target: _blank
    Twitter:
      url: "https://twitter.com/OpisProject"
      target: _blank
  search:
    index: opis_php
    app_id: NMQ2IFNV6E
    app_key: f8653941bd9a6d355cc22fb710a143fe
  styles: [
    "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap",
    "https://fonts.googleapis.com/css?family=Roboto+Mono:400&display=swap",
    "https://use.fontawesome.com/releases/v5.7.2/css/all.css",
    "/assets/next/css/prism.css",
    "/assets/next/css/theme.css",
    "/assets/next/css/style.css"
  ]
  scripts: [
    "https://cdn.jsdelivr.net/npm/algoliasearch@3.32.0/dist/algoliasearchLite.min.js",
    "https://cdn.jsdelivr.net/npm/instantsearch.js@3.0.0/dist/instantsearch.production.min.js",
    "/assets/next/js/prism.js",
    "/assets/next/js/script.js"
  ]


